import Head from 'next/head';
import Image from 'next/image';
import NavBar from '../components/NavBar';
import Main from '../components/Main';
import About from '../components/About';
import Skills from '../components/Skills';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Main />
      <About />
      <Skills />
    </div>
  );
}
